#!/bin/bash

set -e

deno fmt
deno lint

deno test --allow-run --reload

cd ./examples/warandpeace && (
    set -x 
    time ./countwords.sh < ./warandpeace.txt.gz
    time ./countwords.ts < ./warandpeace.txt.gz
    time ./countwords2.ts < ./warandpeace.txt.gz
    echo "a b c d" | ./countwords2.ts || true
    time ./countwords3.ts < ./warandpeace.txt.gz
    echo "a b c d" | ./countwords3.ts || true
)