#!/bin/bash

set -e

HERE="$(realpath "$(dirname $0)")"

deno fmt "$HERE"
deno lint "$HERE"

deno test --allow-run --reload "$HERE"

cd "$HERE/examples/warandpeace" && (
    set -x 
    time ./countwords.sh < ./warandpeace.txt.gz
    time ./countwords.ts < ./warandpeace.txt.gz
    time ./countwords2.ts < ./warandpeace.txt.gz
    echo "a b c d" | ./countwords2.ts || true
    time ./countwords3.ts < ./warandpeace.txt.gz
    echo "a b c d" | ./countwords3.ts || true
)

cd "$HERE/examples/pushiterable" && (
    PATH=".:$PATH" ./example-of-pushiterable.ts
)

cd "$HERE/examples/sounds" && (
    ./sounds.ts
)